### ISSUE TITLE
win10 和windows server 2019下运行一闪而过

### ISSUE THREAD

**Issue by lovestudygithub** [missdeer/coredns_custom_build#10]
win10 和windows server 2019下运行一闪而过，进程里面也看不见，尝试过用管理员身份运行也不行，想请问如何解决？先行谢过！

**Comment by jackflyfly** [comment]
win7默认配置也运行不了，退回旧版正常,用配置文件生成器再重新生成个配置文件就好了。

**Comment by idolyuri** [comment]
> win10 和windows server 2019下运行一闪而过，进程里面也看不见，尝试过用管理员身份运行也不行，想请问如何解决？先行谢过！
删除以下内容就好了
redisc {
        endpoint 127.0.0.1:6379
    }

**Comment by missdeer** [comment]
@lovestudygithub  @jackflyfly  请在cmd中运行，查看输出信息
