### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by test-black** [missdeer/coredns_custom_build#16]
whitelist https://files.krnl.eu/whitelist.txt
不管是直连还是挂代理

**Comment by missdeer** [comment]
ads插件作者不维护了，考虑fork一个自己简单维护

**Comment by missdeer** [comment]
https://github.com/missdeer/coredns_custom_build/commit/6f1809098fbea840c5462eea705173e0f7cc2499
https://github.com/missdeer/coredns_custom_build/commit/6bab512d1a7db77fc493872d0891131f5608e83a
