### ISSUE TITLE
请问一下默认的 health 端口 8080 是否能够自定义？

### ISSUE THREAD

**Issue by huaxianyan** [missdeer/coredns_custom_build#9]
这个端口现在会被 CoreDNS 监听，导致其他使用的服务起不起来，如果为此要修改，多台电脑设备都要改工作量比较大

有没有什么办法可以自定义这个端口，释放 8080 呢？

**Comment by huaxianyan** [comment]
抱歉，发完 issue 仔细看了下配置文件，发现 health 可以手动不启用

**Comment by leopku** [comment]
可改端口
```
health :8053
```
